### ISSUE TITLE
Evaluation tool

### ISSUE THREAD

**Issue by z-jiaming** [max810/XMem2#10]
Hi,

I want to eval the performance of your dataset.
Since the data format is same as DAVIS, could I just use the same tool: [davis2017-evaluation](https://github.com/davisvideochallenge/davis2017-evaluation)?

Thanks!

**Comment by max810** [comment]
We have not used this tool, but you are absolutely right, the dataset follow the same format, so it should work just fine.

Try it, an if it doesn't work, please let us know, we'll update the code/dataset if necessary
