### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by z-jiaming** [max810/XMem2#11]
Hi, 

Sorry to bother you again.
But I found the size of JPEGImages and Annotations in [couple_1_face, full_face_1, half_face_1, half_face_2, pimples] are inconsistent.

So, should I resize the result into the size of Annotations rather than JPEGImages for evaluation?

**Comment by max810** [comment]
Hi,

Thanks for noticing, we'll fix it soon =)

But for now you can just resize everything to 480p (smaller side), this is how we did all our experiments.

**Comment by gauravsethia08** [comment]
Is this resolved? I resize my images to (853, 480) as per the GUI tool, and use the import_existing.py file to reshape my masks, but they are not consistent. 

Image Dimension
![image](https://github.com/max810/XMem2/assets/42647178/fa51986b-5f72-4950-8a6c-5d8d9fc994a6)

Importing Masks
![Screenshot from 2023-10-25 00-36-29](https://github.com/max810/XMem2/assets/42647178/3d709d71-ee87-41f9-a960-6af3b27fa9f5)

Mismatching Mask and Image
![Screenshot from 2023-10-25 00-35-56](https://github.com/max810/XMem2/assets/42647178/d4d3dc09-8ef6-4628-a519-b0100ef5f2bb)

**Comment by z-jiaming** [comment]
I just solve by resizing the image to size of mask.
