### ISSUE TITLE
A short question about models

### ISSUE THREAD

**Issue by 4eJIoBek1** [max810/XMem2#15]
What is difference between XMem.pth, fbrs.pth and s2m.pth?

**Comment by max810** [comment]
Great question! All three are exactly the same as in [the original XMem work](https://github.com/hkchengrex/XMem), so I encourage you to also look them up there.

- `XMem.pth` is the segmentation model itself, with the `key` and `value` encoders, as well as the decoder and sensory memory module.
- `s2m.pth` is the "Scribble to Mask" module, turning the dots and scribbles in the interaction module into a full dense segmentation mask.
- `fbrs.pth` is a module from [f-BRS](https://github.com/SamsungLabs/fbrs_interactive_segmentation) used for the interactive demo. For this one I'm not completely sure of the purpose to be honest.
