### ISSUE TITLE
Run with CPU

### ISSUE THREAD

**Issue by hkaramian** [max810/XMem2#17]
It looks current code is working just with Cuda. Can you add argument to python API and GUI, so we can choose device (cpu / gpu) ? Or give me some hints to make it CPU compatible. 
I'm using a MacBook m2, so can't use Cuda.

Thanks

**Comment by max810** [comment]
Hi,

The code should now run on CPU if CUDA is not available. 

Check it out, and please let me know if there are any more problems with it.
