### ISSUE TITLE
process_video.py not working?

### ISSUE THREAD

**Issue by KaareLJensen** [max810/XMem2#5]
Tried to run your process_video.py script.
Seems like 'frames_with_masks' is not parsed to the run_on_video method?
But still fixing that locally seem just to trigger other run issues.
Can you provide a example that runs and process.

Note: I can run the 'interactive_demo.py' without issues.

**Comment by KaareLJensen** [comment]
So adding to my previous comment, I added 
`    run_on_video(args.video, args.masks, args.output, frames_with_masks)`
in process_video.py. This will add support for 1) multiple input masks frames, 2) not only the first (index 0) video frame mask as input mask.

This starts the run_on_video just fine. But then the parallel image saving causes issues.
I end with "typeerror cannot pickle 'weakref' object" exception.
It seems in that starting both the '_mask_saver_worker' and the '_overlay_saver_worker' will trigger this which is the default.
Adding 'save_overlay=False' will solved the issue, but then only the mask is saved and not the overlay.

I'm a little puzzled as I read the parallel image saver code the implementation seem to follow the documentation. 
But something about starting two processes seem to trigger the 'pickle' exception?

**Comment by KaareLJensen** [comment]
After googling the exception it seems to be a known Python issue
https://github.com/python/cpython/issues/91090
and 
https://stackoverflow.com/a/65749012
triggered in my case by running with Python 3.9.6

**Comment by max810** [comment]
Thank you for detailed analysis @KaareLJensen. Yeah, it seems we have the same problem as in the links you shared. 

I think the easiest solution would be to just not pass the whole `self` object to the workers at [`_save_mask_fn()`](https://github.com/max810/XMem2/blob/main/util/image_saver.py#L262) and [`_save_overlay_fn()`](https://github.com/max810/XMem2/blob/main/util/image_saver.py#L274), and pass only corresponding attributes of `ParallelImageSaver` instance that the worker function needs.

It's weird that everything worked for me in Python 3.9.13, but I'll add this change soon.

**Comment by KaareLJensen** [comment]
I added 
`    def __getstate__(self):
        # To solve issue in python 3.9.6 of multiprocessing.Process instances are unserializable
        # capture what is normally pickled
        state = self.__dict__.copy()

        # remove unpicklable/problematic variables
        # (multiprocessing.Process in this case)
        state['_mask_saver_worker'] = None
        state['_overlay_saver_worker'] = None
        return state
`
to the ParallelImageSaver and this solved the issue.

**Comment by max810** [comment]
Yeah, this is pretty clean.

Could you make a Pull Request? I'll test it and merge it.
